# Generated by cpp11: do not edit by hand

shade_mesh_c <- function(vert, tri, xl, yl, zl, intensity) {
  .Call("_unmeshy_shade_mesh_c", vert, tri, xl, yl, zl, intensity)
}

occlude_mesh_c <- function(vert, tri, xv, yv, zv) {
  .Call("_unmeshy_occlude_mesh_c", vert, tri, xv, yv, zv)
}

project_coords_c <- function(x, y, z, xv, yv, zv, xp, yp, zp) {
  .Call("_unmeshy_project_coords_c", x, y, z, xv, yv, zv, xp, yp, zp)
}

join_triangles <- function(x, y, z) {
  .Call("_unmeshy_join_triangles", x, y, z)
}
